name: 'Check if an open RC or a release PR already exists'
description: 'A GitHub Action to determine if the repository already has a release pr open'
inputs:
  github-token:
    description: 'GitHub Secret Token'
    required: true
outputs:
  is-release-in-progress:
    description: 'True if an open RC or a release PR already exists'
runs:
  using: 'node20'
  main: 'dist/index.js'
