version: 2

updates:
  - package-ecosystem: 'github-actions'
    directories:
      - '/'
      # dependabot only checks for action.yml files in the root directory so we need to add a globstar to all our action directories so dependabot will update them correctly
      # @see https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#directories-or-directory--
      - '/.github/actions/**/*'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'chore'
    groups:
      # Any updates not caught by the group config will get individual PRs
      gha-low-risk:
        update-types:
          - 'minor'
          - 'patch'
    cooldown:
      default-days: 7

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'chore'
    ignore:
      # Prevent updates to ESM-only versions
      - dependency-name: 'chai'
        versions: ['>=5']
      - dependency-name: 'conventional-commits-parser'
        versions: ['>=6']
    groups:
      # Any updates not caught by the group config will get individual PRs
      npm-low-risk:
        update-types:
          - 'minor'
          - 'patch'
    cooldown:
      default-days: 7
