version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      non-breaking:
        update-types:
          - 'minor'
          - 'patch'
