# Probot Settings file
# @see https://probot.github.io/apps/settings/

repository:
  has_issues: true
  has_wiki: false
  default_branch: develop
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: false
  delete_branch_on_merge: true

# Do not set labels in this file as it will apply these labels to all repos and
# remove any labels the repo had before

teams:
  - name: axe-api-team
    permission: push
  - name: axe-api-team-admin
    permission: admin

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
      required_status_checks:
        strict: false
        contexts: ['Security Review']
      enforce_admins: true
  - name: develop
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
      required_status_checks:
        strict: false
        contexts: ['Security Review']
      enforce_admins: true