name: get-issue-url-and-version-number-v1
description: 'A small GitHub Action to get the version number and issue URL for a release candidate'

outputs:
  version-number:
    description: 'The version number for the release candidate'
  issue-url:
    description: 'The issue URL for the release candidate'

runs:
  using: 'node20'
  main: 'dist/index.js'
