name: check-and-move-issue-based-on-labels-v1
description: This action moves the issue based on the label list to the project board's target column
inputs:
  token:
    description: 'A GitHub token with the required permissions'
    required: true
  project-number:
    description: 'The project number of the project board'
    required: true
  target-column:
    description: 'The name of the column where matching issues will be moved to'
    required: true
  issue-number:
    description: 'The issue number to check and move if it matches any'
    required: true
  team-label:
    description: 'The team label name to work only with the team-related issues'
    required: true
  label-prefixes-to-match:
    description: 'Comma-separated list of label prefixes to match (e.g. "QA: required, QA: hold for epic, QA: none")'
    required: false
  need-match-from-each-label-prefix:
    description: 'The flag to check if every value in the "label-prefixes-to-match" should match'
    required: false
  label-prefixes-to-exclude:
    description: 'Comma-separated list of label prefixes that should be excluded (e.g. "QA: failed, QA: not tested")'
    required: false
  need-exclude-from-each-label-prefix:
    description: 'The flag to check if every value in the "label-prefixes-to-exclude" should match'
    required: false

outputs:
  is-issue-moved:
    description: 'The flag to check if the issue is moved'

runs:
  using: 'node20'
  main: 'dist/index.js'
