name: Cancel if Release PR Exists
description: Cancel the parent workflow if a release PR exists a release PR exists
inputs:
  token:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    # Note: Must have repo checked out to use this action
    - name: Exit early if release PR exists
      shell: bash
      run: |
        # -z returns true if the string is empty.
        # If no PRs are found, `gh pr list` will be empty.
        if [ ! -z "$(gh pr list --label release)" ]; then
          echo "Found release PR. Cancelling this workflow.";
          gh pr list --label release;
          gh run cancel ${{ github.run_id }};
          gh run watch ${{ github.run_id }};
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
