name: deploy-release-candidate
description: Preparing a release candidate for QA

inputs:
  version:
    description: A version of the release candidate e.g. "1.0.0"
    required: true
  revision-url:
    description: A commit revision URL
    required: true
  owner:
    description: An owner of the repository e.g. "dequelabs"
    required: true
  repo:
    description: A repository name e.g. "jazzband"
    required: true
  slack-webhook:
    description: A Slack channel webhook URL where the message will be sent
    required: true
  slack-channel:
    description: A Slack channel name where the message will be sent
    required: false

runs:
  using: 'composite'
  steps:
    - uses: dequelabs/axe-api-team-public/.github/actions/get-release-issue-v1@main
      id: get-release-issue
      with:
        version: ${{ inputs.version }}
        owner: ${{ inputs.owner }}
        repo: ${{ inputs.repo }}
      # Check the release issue has been found
    - name: Check the release issue
      shell: bash
      run: |
        if [[ -z "${{ steps.get-release-issue.outputs.issue-url }}" ]]; then
          echo "::error::No release issue has been found"
          exit 1
        fi
    - name: Add a comment to the issue
      shell: bash
      run: gh issue comment ${{ steps.get-release-issue.outputs.issue-url }} --body "$BODY"
      env:
        GH_REPO: ${{ inputs.repo }}
        BODY: "Please use [release candidate build](${{ inputs.revision-url }})"
      # Move an issue to the "Ready for QA" column on the project #66
    - uses: dequelabs/axe-api-team-public/.github/actions/add-to-board-v1@main
      with:
        issue-urls: ${{ steps.get-release-issue.outputs.issue-url }}
        project-number: 66
        column-name: Ready for QA
      # Move an issue to the "RC Created" column on the board project #103
    - uses: dequelabs/axe-api-team-public/.github/actions/add-to-board-v1@main
      with:
        issue-urls: ${{ steps.get-release-issue.outputs.issue-url }}
        project-number: 103
        column-name: RC Created
    - name: Slack notification
      uses: rtCamp/action-slack-notify@b24d75fe0e728a4bf9fc42ee217caa686d141ee8 # tag=v2.2.1
      env:
        SLACK_TITLE: 'RC: ${{ github.event.repository.name }}@v${{inputs.version}} is ready for QA:'
        SLACK_MESSAGE: |
          *Issue:* ${{ steps.get-release-issue.outputs.issue-url }}
          *Build:* ${{ inputs.revision-url }}
        SLACK_COLOR: ${{ job.status }}
        MSG_MINIMAL: 'true'
        SLACK_CHANNEL: ${{ inputs.slack-channel }}
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
