name: create-update-axe-core-pull-request
description: 'A GitHub Action to update axe-core and create a pull request'

inputs:
  token:
    description: '`GITHUB_TOKEN` (permissions `contents: write` and `pull-requests: write`) or a repo scoped Personal Access Token (PAT).'
    required: true
  base:
    description: 'The branch the pull request will be merged into'
    default: 'develop'
  should-checkout:
    description: 'Whether or not the action should checkout the repository'
    default: 'true'
  should-setup-node:
    description: 'Whether or not the action should setup node on behalf of the consumer'
    default: 'true'
    
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      if: ${{ inputs.should-checkout == 'true' }}
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Node
      if: ${{ inputs.should-setup-node == 'true' }}
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: 22
    - id: update-axe-core
      uses: dequelabs/axe-api-team-public/.github/actions/update-axe-core-v1@main
    - name: Open PR
      if: ${{ steps.update-axe-core.outputs.commit-type != null }}
      uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # tag=v5
      with:
        token: ${{ inputs.token }}
        commit-message: '${{ steps.update-axe-core.outputs.commit-type }}: Update axe-core to v${{ steps.update-axe-core.outputs.version }}'
        branch: auto-update-axe-core
        base: ${{ inputs.base }}
        title: '${{ steps.update-axe-core.outputs.commit-type }}: Update axe-core to v${{ steps.update-axe-core.outputs.version }}'
        body: |
          This pull request updates the version of [`axe-core`](https://npmjs.org/axe-core) to v${{ steps.update-axe-core.outputs.version }}.

          This PR was opened by a robot :robot: :tada:.
