name: create-update-axe-core-pull-request
description: 'A GitHub Action to update axe-core and create a pull request'

inputs:
  token:
    description: '`GITHUB_TOKEN` (permissions `contents: write` and `pull-requests: write`) or a repo scoped Personal Access Token (PAT).'
    required: true
  base:
    description: 'The branch the pull request will be merged into'
    default: 'develop'
  should-checkout:
    description: 'Whether or not the action should checkout the repository'
    default: 'true'
  should-setup-node:
    description: 'Whether or not the action should setup node on behalf of the consumer'
    default: 'true'
    
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      if: ${{ inputs.should-checkout == 'true' }}
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Setup Node
      if: ${{ inputs.should-setup-node == 'true' }}
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: 24
    - id: update-axe-core
      uses: dequelabs/axe-api-team-public/.github/actions/update-axe-core-v1@main
    - name: Open PR
      if: ${{ steps.update-axe-core.outputs.commit-type != null }}
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # tag=v5
      with:
        token: ${{ inputs.token }}
        commit-message: '${{ steps.update-axe-core.outputs.commit-type }}: Update axe-core to v${{ steps.update-axe-core.outputs.version }}'
        branch: auto-update-axe-core
        base: ${{ inputs.base }}
        title: '${{ steps.update-axe-core.outputs.commit-type }}: Update axe-core to v${{ steps.update-axe-core.outputs.version }}'
        body: |
          This pull request updates the version of [`axe-core`](https://npmjs.org/axe-core) to v${{ steps.update-axe-core.outputs.version }}.

          This PR was opened by a robot :robot: :tada:.
