name: get-previous-tag-prior-latest
description: 'A GitHub Action to retrieve the previous Git tag before the latest one'

outputs:
  tag:
    description: 'A Git tag name of the previous tag before the latest one (eg. v1.2.3)'
    value: ${{ steps.get-previous-tag.outputs.tag }}
  tag-version:
    description: 'A Git tag version of the previous tag before the latest one (eg. 1.2.3)'
    value: ${{ steps.get-previous-tag.outputs.tag-version }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Fetch all history
        fetch-depth: 0

    - name: Get the previous tag prior to the latest
      id: get-previous-tag
      shell: bash
      run: |
        TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))
        
        # Remove "v" prefix
        TAG_VERSION=${TAG#v}
        
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "tag-version=$TAG_VERSION" >> $GITHUB_OUTPUT
