name: move-released-issues-v1
description: This action moves issues that have been released.
inputs:
  issues-url-list:
    description: The list of released issues URL
    required: true
  project-number:
    description: 'The project number of the project board'
    required: true
  release-column:
    description: 'Column name to move a released issue'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
