name: 'Set Closed Date Field on Issue Action'
description: 'Update a date project field (default: DateClosed) when an issue is closed as completed'
inputs:
  token:
    description: 'Token used for the GH CLI to close and move issue(s) to the correct column. See README for required permissions'
    required: true
  issue-number:
    description: 'The issue number to check'
    required: true
  issue-organization:
    description: 'The organization where the issue is located'
    required: false
  issue-repo:
    description: 'The repository where the issue is located'
    required: false
  project-number:
    description: 'The project number where the issue is located (should be hardcoded in workflow)'
    required: true
  date-field-name:
    description: 'The name of the date field to update the issue close date'
    required: false
    default: 'DateClosed'

runs:
  using: 'node24'
  main: 'dist/index.js'
