name: checkov-scans
description: Checkov scans cloud infrastructure configurations to find misconfigurations before they're deployed and sends a result to Prisma Cloud.

inputs:
  prisma-access-key:
    description: Prisma Cloud access key
    required: true
  prisma-secret-key:
    description: Prisma Cloud secret key
    required: true
  prisma-api-url:
    description: Prisma Cloud API URL
    required: true
  frameworks:
    description: Comma-separated list of frameworks to scan
    required: false
    default: sca_package,github_actions,dockerfile,secrets

runs:
  using: 'composite'
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    # The checkov scan
    - name: Run Prisma Cloud
      id: prisma-cloud
      uses: bridgecrewio/checkov-action@02a4c5d6a02367e5ea493c34c26b094302fd3f61 # tag=v12.3075.0
      with:
        api-key: ${{ inputs.prisma-access-key }}::${{ inputs.prisma-secret-key }}
        # CLI output to the console and md file
        output_format: cli
        framework: ${{ inputs.frameworks }}
        soft_fail_on: LOW
      env:
        PRISMA_API_URL: ${{ inputs.prisma-api-url }}
