name: deploy-release-v1
description: Label all related issues with the package version and create a PR to sync branches

inputs:
  token:
    description: 'A GitHub token with the required permissions'
    required: true
  project-number:
    description: 'A project number of the project board'
    required: false
    default: '66'
  head:
    description: 'A head branch to sync from'
    required: false
    default: main
  base:
    description: 'A target branch for the created pull request'
    required: false
    default: develop
  pr-team-reviewers:
    description: 'Reviewers to tag on the created pull request'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        # Fetch all history
        fetch-depth: 0
    - uses: dequelabs/axe-api-team-public/.github/actions/get-package-version-v1@main
      id: get-package-version
    - uses: dequelabs/axe-api-team-public/.github/actions/generate-commit-list-v1@main
      id: get-commit-list
      with:
        tag: v${{ steps.get-package-version.outputs.version }}
    - uses: dequelabs/axe-api-team-public/.github/actions/label-and-move-released-issues-v1@main
      with:
        commit-list: ${{ steps.get-commit-list.outputs.commit-list }}
        version: ${{ steps.get-package-version.outputs.version }}
        token: ${{ inputs.token }}
        project-number: ${{ inputs.project-number }}
    - uses: dequelabs/action-sync-branches@master
      with:
        github-token: ${{ inputs.token }}
        pr-title: 'chore: merge ${{ inputs.head }} into ${{ inputs.base }}'
        pr-body: 'Remember to _merge_ (rather than squash) this PR! Also, auto-merge does not work because many of the required checks do not run on the `${{ inputs.head }}` branch.'
        pr-team-reviewers: ${{ inputs.pr-team-reviewers }}
        head: ${{ inputs.head }}
        base: ${{ inputs.base }}
