name: release-candidate-ready-for-qa-v1
description: Lets the QA team know a release candidate is ready for QA

inputs:
  sha-rc:
    description: 8 characters SHA of the release commit from the release branch
    required: false
  slack-webhook:
    description: A Slack channel webhook URL where the message will be sent
    required: false
  slack-channel:
    description: A Slack channel where the message will be sent
    required: false
  release-issue-project-number:
    description: The project number where the release issue is created
    required: true
  release-issue-column-name:
    description: The column name where the release issue is moved to (e.g. "QAToDo")
    required: true

runs:
  using: 'composite'
  steps:
    - name: Validate required inputs
      shell: bash
      env:
        INPUTS_JSON: ${{ toJSON(inputs) }}
      run: |
        echo "Validating required inputs..."

        # Get all required inputs from this action.yml file
        required_inputs=$(yq eval '.inputs | to_entries | .[] | select(.value.required == true) | .key' ${{ github.action_path }}/action.yml)

        missing_inputs=()

        # Check each required input
        for input in $required_inputs; do
          value=$(echo "$INPUTS_JSON" | jq -r --arg key "$input" '.[$key] // empty')

          if [ -z "$value" ] || [ "$value" = "null" ]; then
            echo "::error::Required input '$input' is missing"
            missing_inputs+=("$input")
          else
            echo "✓ Required input '$input' is present"
          fi
        done

        if [ ${#missing_inputs[@]} -gt 0 ]; then
          exit 1
        fi

        echo "All required inputs are present"

    - uses: dequelabs/axe-api-team-public/.github/actions/get-package-version-v1@main
      id: get-package-version
    - uses: dequelabs/axe-api-team-public/.github/actions/get-release-issue-v1@main
      id: get-release-issue
      with:
        version: ${{ steps.get-package-version.outputs.version }}
    - name: Check a release issue is found
      shell: bash
      run: |
        if [[ -z "${{ steps.get-release-issue.outputs.issue-url }}" ]]; then
          echo "::error::No release issue has been found"
          exit 1
        fi
    - name: Get SHA of the release commit
      id: get-sha-rc
      shell: bash
      run: |
        SHA_RC="${{ inputs.sha-rc }}"
        
        if [ -z "$SHA_RC" ]; then
          SHA_RC=$(git rev-parse --short=8 HEAD)
        fi
        
        echo "sha-release-commit=$SHA_RC" >> $GITHUB_OUTPUT
    - name: Set a build name
      id: set-build-name
      shell: bash
      # build-name = dequelabs/axe-core-npm-4.8.5-rc-1540d5ae (this is just example)
      run: echo "build-name=$(cat package.json | jq -r '.name')-${{ steps.get-package-version.outputs.version }}-rc-${{ steps.get-sha-rc.outputs.sha-release-commit }}" >> $GITHUB_OUTPUT
    - name: Add a comment to the issue
      shell: bash
      run: gh issue comment ${{ steps.get-release-issue.outputs.issue-url }} --body "$BODY"
      env:
        BODY: "Please use the release candidate build: ${{ steps.set-build-name.outputs.build-name }}"
      # Move an issue to the `release-issue-column-name` column on the board project `release-issue-project-number`
    - uses: dequelabs/axe-api-team-public/.github/actions/add-to-board-v1@main
      with:
        issue-urls: ${{ steps.get-release-issue.outputs.issue-url }}
        project-number: ${{ inputs.release-issue-project-number }}
        column-name: ${{ inputs.release-issue-column-name }}
    - name: Slack notification
      if: inputs.slack-channel != '' && inputs.slack-webhook != ''
      uses: rtCamp/action-slack-notify@b24d75fe0e728a4bf9fc42ee217caa686d141ee8 # tag=v2.2.1
      env:
        SLACK_TITLE: 'RC: "${{ steps.set-build-name.outputs.build-name }}" is ready for QA:'
        SLACK_MESSAGE: |
          *Issue:* ${{ steps.get-release-issue.outputs.issue-url }}
          *Build:* ${{ steps.set-build-name.outputs.build-name }}
        SLACK_COLOR: ${{ job.status }}
        MSG_MINIMAL: 'true'
        SLACK_CHANNEL: ${{ inputs.slack-channel }}
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
