name: release-candidate-ready-for-qa-v1
description: Lets the QA team know a release candidate is ready for QA

inputs:
  sha-rc:
    description: 8 characters SHA of the release commit from the release branch
    required: false
  slack-webhook:
    description: A Slack channel webhook URL where the message will be sent
    required: true

runs:
  using: 'composite'
  steps:
    - uses: dequelabs/axe-api-team-public/.github/actions/get-package-version-v1@main
      id: get-package-version
    - uses: dequelabs/axe-api-team-public/.github/actions/get-release-issue-v1@main
      id: get-release-issue
      with:
        version: ${{ steps.get-package-version.outputs.version }}
    - name: Check a release issue is found
      shell: bash
      run: |
        if [[ -z "${{ steps.get-release-issue.outputs.issue-url }}" ]]; then
          echo "::error::No release issue has been found"
          exit 1
        fi
    - name: Get SHA of the release commit
      id: get-sha-rc
      shell: bash
      run: |
        SHA_RC="${{ inputs.sha-rc }}"
        
        if [ -z "$SHA_RC" ]; then
          SHA_RC=$(git rev-parse --short=8 HEAD)
        fi
        
        echo "sha-release-commit=$SHA_RC" >> $GITHUB_OUTPUT
    - name: Set a build name
      id: set-build-name
      shell: bash
      # build-name = dequelabs/axe-core-npm-4.8.5-rc-1540d5ae (this is just example)
      run: echo "build-name=$(cat package.json | jq -r '.name')-${{ steps.get-package-version.outputs.version }}-rc-${{ steps.get-sha-rc.outputs.sha-release-commit }}" >> $GITHUB_OUTPUT
    - name: Add a comment to the issue
      shell: bash
      run: gh issue comment ${{ steps.get-release-issue.outputs.issue-url }} --body "$BODY"
      env:
        BODY: "Please use the release candidate build: ${{ steps.set-build-name.outputs.build-name }}"
      # Move an issue to the "In QA" column on the board project #103
    - uses: dequelabs/axe-api-team-public/.github/actions/add-to-board-v1@main
      with:
        issue-urls: ${{ steps.get-release-issue.outputs.issue-url }}
        project-number: 103
        column-name: In QA
    - name: Slack notification
      uses: rtCamp/action-slack-notify@b24d75fe0e728a4bf9fc42ee217caa686d141ee8 # tag=v2.2.1
      env:
        SLACK_TITLE: 'RC: "${{ steps.set-build-name.outputs.build-name }}" is ready for QA:'
        SLACK_MESSAGE: |
          *Issue:* ${{ steps.get-release-issue.outputs.issue-url }}
          *Build:* ${{ steps.set-build-name.outputs.build-name }}
        SLACK_COLOR: ${{ job.status }}
        MSG_MINIMAL: 'true'
        SLACK_CHANNEL: api-team-releases
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
