name: Add to Board
description: A GitHub Action to move issues to a specific column on a project board
inputs:
  issue-urls:
    description: 'Comma delimited list of issue urls to add to the project board'
    required: true
  project-number:
    description: 'The project board number to add the issue to'
    default: '66'
  column-name:
    description: 'Name of column to add to'
    default: 'Backlog'
runs:
  using: 'node20'
  main: 'dist/index.js'
