name: Add to Board
description: Add and Move specific item(s) to a project board
inputs:
  issue-url:
    description: 'A single issue URL, or a stringified list of URLS the board'
    required: true
  project-number:
    description: 'The project board number to add the issue to'
    default: '66'
  column-name:
    description: 'Name of column to add to'
    default: 'Backlog'
runs:
  using: 'node20'
  main: 'dist/index.js'
