name: 'Update axe-core'
description: 'A GitHub action for updating axe-core to the latest stable version'
outputs:
  commit-type:
    description: 'The SemVer type of the axe-core update. Is `null` if no update occurred'
runs:
  using: 'node20'
  main: 'dist/index.js'