name: abort-release-candidate
description: 'A GitHub Action to abort a release candidate'

inputs:
  token:
    description: 'Token used for the GH CLI to close and move issue(s) to the correct column. See README for required permissions'
    required: true
  base:
    description: 'The branch the release candidate will be merged into'
    required: true
  docs-repo:
    description: 'The docs repository where the issue for the release candidate is located'
    default: ''
    required: false
  version:
    description: 'The release candidate version number that will be aborted (e.g 1.0.0)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        # Fetch all history
        fetch-depth: 0
        # Checkout the release branch so we can get the release candidate version and reset it to the base branch later
        ref: 'release'
        # PAT has required permissions force pushing when the `release` branch is checked out
        token: ${{ inputs.token }}

    - name: Get release candidate version
      shell: bash
      id: get-release-candidate-version
      run: |
        VERSION="${{ inputs.version }}"
        
        if [ -z "$VERSION" ]; then
          # Get the version number from the prepare_release shell script and set it as an output
          # Monorepos have a lerna.json file that contains the updated version number
          # Non-monorepos, or non-npm repos, have a package.json file that contains the updated version number
          if [ -f "lerna.json" ]; then
            VERSION=$(cat lerna.json | jq -r '.version')
          else
            VERSION=$(cat package.json | jq -r '.version')
          fi
        fi

        echo "The release candidate version: $VERSION"
        echo "release_candidate_version=$VERSION" >> $GITHUB_OUTPUT

    - name: Get release candidate issue url
      uses: dequelabs/axe-api-team-public/.github/actions/get-release-issue-v1@main
      id: get-release-issue
      with:
        version: ${{ steps.get-release-candidate-version.outputs.release_candidate_version }}
      env:
        GH_TOKEN: ${{ inputs.token }}

    - name: Close release candidate issue as `Not Planned`
      if: steps.get-release-issue.outputs.issue-url != null
      shell: bash
      run: |
        gh issue close ${{ steps.get-release-issue.outputs.issue-url }} -r "not planned"
      env:
        GH_TOKEN: ${{ inputs.token }}

    - name: Move release candidate issue to `No` column (Board 188)
      if: steps.get-release-issue.outputs.issue-url != null
      uses: dequelabs/axe-api-team-public/.github/actions/add-to-board-v1@main
      with:
        issue-urls: ${{ steps.get-release-issue.outputs.issue-url }}
        column-name: 'No'
        project-number: '188'
      env:
        GH_TOKEN: ${{ inputs.token }}

    - name: Get release candidate issue url from docs-repo
      if: inputs.docs-repo != ''
      uses: dequelabs/axe-api-team-public/.github/actions/get-release-issue-v1@main
      id: get-release-issue-from-docs-repo
      with:
        version: ${{ steps.get-release-candidate-version.outputs.release_candidate_version }}
        repo: ${{ inputs.docs-repo }}
      env:
        GH_TOKEN: ${{ inputs.token }}

    - name: Close release candidate issue as `Not Planned` in docs-repo
      # Guard against empty issue url if the issue was not found in the previous step
      if: inputs.docs-repo != '' && steps.get-release-issue-from-docs-repo.outputs.issue-url != null
      shell: bash
      run: |
        gh issue close ${{ steps.get-release-issue-from-docs-repo.outputs.issue-url }} -r "not planned"
      env:
        GH_TOKEN: ${{ inputs.token }}

    - name: Move release candidate doc issue to `Cancelled` column (Board 193)
      if: inputs.docs-repo != '' && steps.get-release-issue-from-docs-repo.outputs.issue-url != null
      uses: dequelabs/axe-api-team-public/.github/actions/add-to-board-v1@main
      with:
        issue-urls: ${{ steps.get-release-issue-from-docs-repo.outputs.issue-url }}
        column-name: 'Cancelled'
        project-number: '193'
      env:
        GH_TOKEN: ${{ inputs.token }}

    - name: Reset release branch to ${{ inputs.base }}
      shell: bash
      run: |
        git reset --hard "origin/${{ inputs.base }}"
        git push --force origin release
