name: Automatically create patch release every 2 weeks
description: Triggered on schedule by our integrations to patch release
inputs:
  release-command:
    required: true
    type: string
  release-branch:
    required: true
    type: string
  default-branch:
    required: true
    type: string
  token:
    required: true
    type: string
  project_token:
    required: true
    type: string
  slack_webhook:
    required: true
    type: string
  odd_release:
    required: false
    type: string
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.default-branch }}
        token: ${{ inputs.token }}
        fetch-depth: 0

    - name: Create QA issue
      uses: dacbd/create-issue-action@ba4d1c45cccf9c483f2720cefb40e437f0ee6f7d
      id: new-issue
      with:
        token: ${{ inputs.token }}
        title: "TESTING"
    - name: Store issue URL
      id: issue-url
      shell: bash
      run: |
        url="$(echo $json | jq .html_url | sed 's/"//g' )"
        echo "url=$url" >> $GITHUB_OUTPUT
      env:
        json: ${{  steps.new-issue.outputs.json  }}
    - name: Save issue-id
      id: issue-id
      shell: bash
      run: |
        issueId="$(echo $json | jq -r .node_id)"
        echo "id=$issueId" >> "$GITHUB_OUTPUT"
      env:
        json: ${{  steps.new-issue.outputs.json  }}
    - name: Move to board
      uses: dequelabs/axe-api-team-public/.github/actions/add-to-board-v1@test1
      with:
        token: ${{ inputs.project_token }}
        issue-id: ${{ steps.issue-id.outputs.id }}
        # 66 taken from the url: https://github.com/orgs/dequelabs/projects/66
        project-number: 66
